application: tubetapes
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /scripts
  static_dir: scripts #local name
  secure: optional

- url: /images
  static_dir: images #local name
  secure: optional

- url: /.*
  script: app.app
  secure: optional

libraries:
- name: jinja2
  version: latest

